# Generated by Django 4.1.5 on 2023-01-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='age_varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_btw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gender_varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='statics/people')),
                ('name', models.CharField(max_length=100)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.age_varient')),
                ('gender_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.gender_varient')),
                ('occupation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.occupations')),
                ('places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.place')),
            ],
        ),
    ]
